# Generated by Django 6.0.7 on 2026-07-16 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('business', models.CharField(blank=True, max_length=200)),
                ('state', models.CharField(max_length=2)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('legal_agreement', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('contacted', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
    ]
